# Using ``addAccis()`` to apply adaptive setpoint temperatures

We are going to apply the adaptive setpoint temperatures to the IDF "TestModel_onlyGeometryForVRFsystem_2zones_CalcVent_V2510" (a model for EnergyPlus 25.1), which can be found in the folder ``sample IDFs/input_IDFs`` of the sample files. For clarity purposes, it has been renamed to "TestModel.idf". ``addAccis()`` does not run any simulation, but it needs the EnergyPlus version of the IDF (25.1) to be installed, since it reads its IDD file.

First of all, let's see what files we do have in the folder:

In [1]:
import os
os.listdir()

['TestModel.idf', 'using_addAccis.ipynb', '__init__.py']

You can see there is/are a/some IDF file/files there, which is/are:

In [2]:
input_idf = [i for i in os.listdir() if i.endswith('.idf')]
print(*input_idf, sep='\n')

TestModel.idf

So, let's apply adaptive setpoint temperatures.

## 1. General use

### 1.1 Short version

First, let's do this using the short version. When we run the code below (not entering any argument), accim will request some information to generate the output idfs. We are going to enter the following information in **bold**:

Enter the ScriptType (
for VRFsystem with full air-conditioning mode: vrf_ac;
for VRFsystem with mixed-mode: vrf_mm;
for ExistingHVAC with mixed mode: ex_mm;
for ExistingHVAC with full air-conditioning mode: ex_ac
): **vrf_mm**

Enter the SupplyAirTempInputMethod (
for Supply Air Temperature: supply air temperature;
for Temperature Difference: temperature difference;
): **temperature difference**

Do you want to keep the existing outputs (true or false)?: **false**

Enter the Output type (standard, simplified, detailed or custom): **standard**

Enter the Output frequencies separated by space (timestep, hourly, daily, monthly, runperiod): **hourly runperiod**

Do you want to generate a dataframe to see all outputs? (true or false): **false**

Enter the EnergyPlus version (9.1 to 26.2, or auto): **auto** (accim reads the version from the IDF, 25.1 in this case)

Enter the Temperature Control method (temperature or pmv): **temperature**

Then, accim will report the information we just entered, and will start generating a generic idf file, which will be modified based on the remaining arguments accim will request in a second stage. Again, we are going to enter the following information in **bold**:

Enter the Comfort Standard numbers separated by space (...): **1 14**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

Enter the Category numbers separated by space (...): **1 2 3 80 90**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

Enter the Comfort Mode numbers separated by space (...): **0 0.1 0.2 0.3 0.4 0.5 1 1.1 1.2 1.3 1.4 1.5 2 3**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

Enter the setpoint accuracy number (any number greater than 0, if omitted will be 10000): **100**

Are you sure the number is correct? [y or [] / n]: **(just hit enter)**

Enter the number for the CAT cooling offset modifier (value will be summed to the ACST, if omitted will be 0): **0**

Are you sure the number is correct? [y or [] / n]: **(just hit enter)**

Enter the number for the CAT heating offset modifier (value will be summed to the AHST, if omitted will be 0): **0**

Are you sure the number is correct? [y or [] / n]: **(just hit enter)**

Enter the start of the cooling season in numeric date format dd/mm or the day of the year: **01/11**

Are you sure the number is correct? [y or [] / n]: **(just hit enter)**

Enter the end of the cooling season in numeric date format dd/mm or the day of the year: **01/03**

Are you sure the number is correct? [y or [] / n]: **(just hit enter)**

Enter the HVAC Mode numbers separated by space (...): **2**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)** 

Enter the Ventilation Control numbers separated by space (...): **2**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)** 

Enter the maximum temperature difference number for Ventilation Opening Factor (any number larger than 0): **20**

Are you sure the number is correct? [y or [] / n]: **(just hit enter)**

Enter the minimum temperature difference number for Ventilation Opening Factor (any number larger than 0 and smaller than the maximum temperature difference number): **1**

Are you sure the number is correct? [y or [] / n]: **(just hit enter)**

Enter the multiplier number for Ventilation Opening Factor (any number between 0 and 1): **0.2**

Are you sure the number is correct? [y or [] / n]: **(just hit enter)**

Enter the VSToffset numbers separated by space (if omitted, will be 0): **(just hit enter)**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

Enter the MinOToffset numbers separated by space (if omitted, will be 50): **(just hit enter)**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

Enter the MaxWindSpeed numbers separated by space (if omitted, will be 50): **(just hit enter)**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

Enter the ASTtol value from (if omitted, will be 0.1): **(just hit enter)**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

Enter the ASTtol value to (if omitted, will be 0.1): **(just hit enter)**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

Enter the ASTtol value steps (if omitted, will be 0.1): **(just hit enter)**

Are you sure the numbers are correct? [y or [] / n]: **(just hit enter)**

And finally, after listing the output IDFs:

Do you still want to run ACCIS? [y/n]: **y**

In [3]:
from accim.sim import accis
accis.addAccis()

--------------------------------------------------------
Adaptive-Comfort-Control-Implemented Model (ACCIM) v0.8.2
--------------------------------------------------------

This tool allows to apply adaptive setpoint temperatures.
For further information, please read the documentation:
https://accim.readthedocs.io/en/master/
For a visual understanding of the tool, please visit the following jupyter notebooks:
-    Using addAccis() to apply adaptive setpoint temperatures
https://accim.readthedocs.io/en/master/jupyter_notebooks/addAccis/using_addAccis.html
-    Using rename_epw_files() to rename the EPWs for proper data analysis after simulation
https://accim.readthedocs.io/en/master/jupyter_notebooks/rename_epw_files/using_rename_epw_files.html
-    Using runEp() to directly run simulations with EnergyPlus
https://accim.readthedocs.io/en/master/jupyter_notebooks/runEp/using_runEp.html
-    Using the class Table() for data analysis
https://accim.readthedocs.io/en/master/jupyter_notebooks/Table/using_Table.html
-    Full example
https://accim.readthedocs.io/en/master/jupyter_notebooks/full_example_IBPSA/full_example_IBPSA.html

Starting with the process.

Now, you are going to be asked to enter some information for different arguments to generate the output IDFs with adaptive setpoint temperatures.
If you are not sure about how to use these parameters, please take a look at the documentation in the following link:
https://accim.readthedocs.io/en/master/4_detailed%20use.html

Please, enter the following information:

Enter the ScriptType (
for VRFsystem with full air-conditioning mode: vrf_ac;
for VRFsystem with mixed-mode: vrf_mm;
for ExistingHVAC with mixed mode: ex_mm;
for ExistingHVAC with full air-conditioning mode: ex_ac
): vrf_mm

Enter the SupplyAirTempInputMethod (
for Supply Air Temperature: supply air temperature;
for Temperature Difference: temperature difference;
): temperature difference

Do you want to keep the existing outputs (true or false)?: false

Enter the Output type (standard, simplified, detailed or custom): standard

Enter the Output frequencies separated by space (timestep, hourly, daily, monthly, runperiod): hourly runperiod

Do you want to generate a dataframe to see all outputs? (true or false): false

Enter the EnergyPlus version (9.1 to 26.2, or auto): auto

Enter the Temperature Control method (temperature or pmv): temperature
Basic input data:
ScriptType is: vrf_mm
Supply Air Temperature Input Method is: temperature difference
Output type is: standard
Output frequencies are:
['hourly', 'runperiod']
Temperature Control method is: temperature

=======================START OF GENERIC IDF FILE GENERATION PROCESS=======================

Starting with file:
TestModel
IDD location is: C:\EnergyPlusV25-1-0\Energy+.idd

The occupied zones in the model TestModel are:
Block1:Zone1
Block1:Zone2
The windows and doors in the model TestModel are:
Block1_Zone2_Wall_3_0_0_0_0_0_Win
Block1_Zone2_Wall_4_0_0_0_0_0_Win
Block1_Zone2_Wall_5_0_0_0_0_0_Win
Block1_Zone1_Wall_2_0_0_0_0_0_Win
Block1_Zone1_Wall_3_0_0_0_0_0_Win
Block1_Zone1_Wall_5_0_0_0_0_0_Win
The zones in the model TestModel are:
Block1_Zone1
Block1_Zone2
The people objects in the model have been amended.
Block1:Zone1 Thermostat has been added
Block1:Zone2 Thermostat has been added
On Schedule already was in the model
TypOperativeTempControlSch Schedule already was in the model
All ZoneHVAC:IdealLoadsAirSystem Heating and Cooling availability schedules has been set to on
On 24/7 Schedule already was in the model
Control type schedule: Always 4 Schedule has been added
Relative humidity setpoint schedule: Always 50.00 Schedule has been added
Heating Fanger comfort setpoint: Always -0.5 Schedule has been added
Cooling Fanger comfort setpoint: Always  0.1 Schedule has been added
Zone CO2 setpoint: Always 900ppm Schedule has been added
Min CO2 concentration: Always 600ppm Schedule has been added
Generic contaminant setpoint: Always 0.5ppm Schedule has been added
Air distribution effectiveness (always 1) Schedule has been added
VRF Heating Cooling (Northern Hemisphere) Schedule has been added
DefaultFanEffRatioCurve Curve:Cubic Object has been added
VRFTUCoolCapFT Curve:Cubic Object has been added
VRFTUHeatCapFT Curve:Cubic Object has been added
VRFCoolCapFTBoundary Curve:Cubic Object has been added
VRFCoolEIRFTBoundary Curve:Cubic Object has been added
CoolingEIRLowPLR Curve:Cubic Object has been added
VRFHeatCapFTBoundary Curve:Cubic Object has been added
VRFHeatEIRFTBoundary Curve:Cubic Object has been added
HeatingEIRLowPLR Curve:Cubic Object has been added
DefaultFanPowerRatioCurve Curve:Exponent Object has been added
DXHtgCoilDefrostEIRFT Curve:Biquadratic Object has been added
VRFCoolCapFT Curve:Biquadratic Object has been added
VRFCoolCapFTHi Curve:Biquadratic Object has been added
VRFCoolEIRFT Curve:Biquadratic Object has been added
VRFCoolEIRFTHi Curve:Biquadratic Object has been added
VRFHeatCapFT Curve:Biquadratic Object has been added
VRFHeatCapFTHi Curve:Biquadratic Object has been added
VRFHeatEIRFT Curve:Biquadratic Object has been added
VRFHeatEIRFTHi Curve:Biquadratic Object has been added
CoolingLengthCorrectionFactor Curve:Biquadratic Object has been added
VRF Piping Correction Factor for Length in Heating Mode Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Energy Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Energy Modifier Curve:Biquadratic Object has been added
VRFACCoolCapFFF Curve:Quadratic Object has been added
CoolingEIRHiPLR Curve:Quadratic Object has been added
VRFCPLFFPLR Curve:Quadratic Object has been added
HeatingEIRHiPLR Curve:Quadratic Object has been added
CoolingCombRatio Curve:Linear Object has been added
HeatingCombRatio Curve:Linear Object has been added
VRF Outdoor Unit_Block1:Zone1 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone2 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone1 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone1 Zone List Object has been added
VRF Outdoor Unit_Block1:Zone2 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone2 Zone List Object has been added
Block1:Zone1 Sizing:Zone Object has been added
Block1:Zone2 Sizing:Zone Object has been added
Block1:Zone1 Design Specification Outdoor Air Object has been added
Block1:Zone2 Design Specification Outdoor Air Object has been added
Block1:Zone1 Design Specification Zone Air Distribution Object has been added
Block1:Zone2 Design Specification Zone Air Distribution Object has been added
Block1:Zone1 Nodelist Objects has been added
Block1:Zone2 Nodelist Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone1 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone2 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Fan:ConstantVolume Object has been added
Block1:Zone2 Fan:ConstantVolume Object has been added
Vent_SP_temp Schedule has been added
AHST_Sch_Block1_Zone2 Schedule has been added
ACST_Sch_Block1_Zone2 Schedule has been added
AHST_Sch_Block1_Zone1 Schedule has been added
ACST_Sch_Block1_Zone1 Schedule has been added
Added - SetComfTemp Program
Added - CountHours_Block1_Zone2 Program
Added - CountHours_Block1_Zone1 Program
Added - SetAppLimits Program
Added - ApplyCAT Program
Added - SetAST_Master Program with 109 lines

Added - 46 per-ComfStand SetAST subprograms
Added - SetAST Program (base program that calls SetAST_Master)
Added - SetASTnoTol Program
Added - InitASTvariables Program
Added - CountHoursNoApp_Block1_Zone2 Program
Added - SetGeoVarBlock1_Zone2 Program
Added - CountHoursNoApp_Block1_Zone1 Program
Added - SetGeoVarBlock1_Zone1 Program
Added - SetInputData Program
Added - SetVOFinputData Program
Added - SetVST Program
Added - ApplyAST_Block1_Zone2 Program
Added - ApplyAST_Block1_Zone1 Program
Added - SetMyVOF_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - Comfort Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature Output Variable
Added - Adaptive Heating Setpoint Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature_No Tolerance Output Variable
Added - Adaptive Heating Setpoint Temperature_No Tolerance Output Variable
[... 310 lines not shown in the documentation ...]
Added Output:Meter for Cooling:Electricity (runperiod)
Modified - SimulationControl object: enabled Zone, System, and Plant Sizing Calculations
IDF has been saved
Ending with file:
TestModel

=======================END OF GENERIC IDF FILE GENERATION PROCESS=======================

The following IDFs will not work, and therefore these will be deleted:
None

=======================START OF OUTPUT IDF FILES GENERATION PROCESS=======================

The information you will be required to enter below will be used to generate the customised output IDFs:

Enter the Comfort Standard numbers separated by space (
0 = ESP CTE;
1 = INT EN16798-1;
2 = INT ASHRAE55;
3 = JPN Rijal;
4 = CHN GBT50785 Cold;
5 = CHN GBT50785 HotMild;
6 = CHN Yang;
7 = IND IMAC C NV;
8 = IND IMAC C MM;
9 = IND IMAC R 7DRM;
10 = IND IMAC R 30DRM;
11 = IND Dhaka;
12 = ROM Udrea;
13 = AUS Williamson;
14 = AUS DeDear;
15 = BRA Rupp NV;
16 = BRA Rupp AC;
17 = MEX Oropeza Arid;
18 = MEX Oropeza DryTropic;
19 = MEX Oropeza Temperate;
20 = MEX Oropeza HumTropic;
21 = CHL Perez-Fargallo;
22 = INT ISO7730;
99 = CUSTOM;
Please refer to the full list of setpoint temperatures at https://htmlpreview.github.io/?https://github.com/dsanchez-garcia/accim/blob/master/docs/source/html_files/full_setpoint_table.html
): 1 14
          Are you sure the numbers are correct? [y or [] / n]:


For the comfort standard 1 = INT EN16798, the available categories you can choose are:
1 = EN16798 Category I
2 = EN16798 Category II
3 = EN16798 Category III
For the comfort standard 14 = AUS DeDear, the available categories you can choose are:
80 = 80% acceptability
90 = 90% acceptability
Enter the Category numbers separated by space (
1 = CAT I / CAT A;
2 = CAT II / CAT B;
3 = CAT III / CAT C;
80 = 80% ACCEPT;
90 = 90% ACCEPT;
Please refer to the full list of setpoint temperatures at https://htmlpreview.github.io/?https://github.com/dsanchez-garcia/accim/blob/master/docs/source/html_files/full_setpoint_table.html
):1 2 3 80 90
          Are you sure the numbers are correct? [y or [] / n]:


For the comfort standard 1 = INT EN16798, the available ComfMods you can choose are:
0 = EN16798 Static setpoints
1 = EN16798 Adaptive setpoints when applicable, otherwise CTE
2 = EN16798 Adaptive setpoints when applicable, otherwise EN16798 Static setpoints
3 = EN16798 Adaptive setpoints when applicable, otherwise EN16798 Adaptive setpoints horizontally extended
For the comfort standard 14 = AUS DeDear, the available ComfMods you can choose are:
0.1 = Australian Building Code Static setpoints for climate zones 1, 2 and 3
0.2 = Australian Building Code Static setpoints for climate zone 4
0.3 = Australian Building Code Static setpoints for climate zone 5
0.4 = Australian Building Code Static setpoints for climate zones 6 and 7
0.5 = Australian Building Code Static setpoints for climate zone 8
1.1 = DeDear Model Adaptive setpoints when applicable, otherwise Australian Building Code Static setpoints for climate zones 1, 2 and 3
1.2 = DeDear Model Adaptive setpoints when applicable, otherwise Australian Building Code Static setpoints for climate zone 4
1.3 = DeDear Model Adaptive setpoints when applicable, otherwise Australian Building Code Static setpoints for climate zone 5
1.4 = DeDear Model Adaptive setpoints when applicable, otherwise Australian Building Code Static setpoints for climate zones 6 and 7
1.5 = DeDear Model Adaptive setpoints when applicable, otherwise Australian Building Code Static setpoints for climate zone 8
2 = DeDear Model Adaptive setpoints when applicable, otherwise ISO 7730 Static setpoints
3 = DeDear Model Adaptive setpoints when applicable, otherwise Adaptive setpoints horizontally extended
Enter the Comfort Mode numbers separated by space (
0 or 0.X = Static;
1, 1.X, 2, 3 = Adaptive;
Please refer to the full list of setpoint temperatures at https://htmlpreview.github.io/?https://github.com/dsanchez-garcia/accim/blob/master/docs/source/html_files/full_setpoint_table.html
): 0 0.1 0.2 0.3 0.4 0.5 1 1.1 1.2 1.3 1.4 1.5 2 3
          Are you sure the numbers are correct? [y or [] / n]:

Enter the setpoint accuracy number (any number greater than 0, if omitted will be 10000): 100
          Are you sure the number is correct? [y or [] / n]:

Enter the number for the CAT cooling offset modifier (value will be summed to the ACST, if omitted will be 0): 0
          Are you sure the number is correct? [y or [] / n]:

Enter the number for the CAT heating offset modifier (value will be summed to the AHST, if omitted will be 0): 0
          Are you sure the number is correct? [y or [] / n]:

Enter the start of the cooling season in numeric date format dd/mm or the day of the year: 01/11
          Are you sure the number is correct? [y or [] / n]:

Enter the end of the cooling season in numeric date format dd/mm or the day of the year: 01/03
          Are you sure the number is correct? [y or [] / n]:

Enter the HVAC Mode numbers separated by space (
0 = Fully Air-conditioned;
1 = Naturally ventilated;
2 = Mixed Mode;
): 2
          Are you sure the numbers are correct? [y or [] / n]:

Enter the Ventilation Control numbers separated by space (
If HVACmode = 1:
   0 = Ventilates above neutral temperature;
   1 = Ventilates above upper comfort limit;
If HVACmode = 2:
   0 = Ventilates above neutral temperature and fully opens doors and windows;
   1 = Ventilates above lower comfort limit and fully opens doors and windows;
   2 = Ventilates above neutral temperature and opens doors and windows based on the customised venting opening factor;
   3 = Ventilates above lower comfort limit and opens doors and windows based on the customised venting opening factor;
): 2
          Are you sure the numbers are correct? [y or [] / n]:
Enter the maximum temperature difference number for Ventilation Opening Factor (any number larger than 0): 20
          Are you sure the number is correct? [y or [] / n]:
Enter the minimum temperature difference number for Ventilation Opening Factor (any number larger than 0 and smaller than the maximum temperature difference number): 1
          Are you sure the number is correct? [y or [] / n]:
Enter the multiplier number for Ventilation Opening Factor (any number between 0 and 1): 0.2
          Are you sure the number is correct? [y or [] / n]:

Enter the VSToffset numbers separated by space (if omitted, will be 0):
          Are you sure the numbers are correct? [y or [] / n]:

Enter the MinOToffset numbers separated by space (if omitted, will be 50):
          Are you sure the numbers are correct? [y or [] / n]:

Enter the MaxWindSpeed numbers separated by space (if omitted, will be 50):
          Are you sure the numbers are correct? [y or [] / n]:

Enter the ASTtol value from (if omitted, will be 0.1):
          Are you sure the numbers are correct? [y or [] / n]:
Enter the ASTtol value to (if omitted, will be 0.1):
          Are you sure the numbers are correct? [y or [] / n]:
Enter the ASTtol value steps (if omitted, will be 0.1):
          Are you sure the numbers are correct? [y or [] / n]:
The list of output IDFs is going to be:
TestModel[CS_INT EN16798[CA_1[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
And the total number of output IDFs is going to be 36
Do you still want to run ACCIS? [y/n]: y
Generating the following output IDF files:
TestModel[CS_INT EN16798[CA_1[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf

TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf

=======================END OF OUTPUT IDF FILES GENERATION PROCESS=======================

Let's see what files we do have now in the folder:

In [4]:
os.listdir()

['TestModel.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_1[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_1[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_1[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_1[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_2[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_2[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_2[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_2[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_3[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_3[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_3[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_3[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'using_addAccis.ipynb',
 '__init__.py']

We can see there are new IDFs, as stated previously in the python console:

In [5]:
output_idfs = [i for i in os.listdir() if not(any(i in j for j in input_idf)) and i.endswith('.idf')]
print(*output_idfs, sep='\n')

TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3.0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf

Now, these are ready for simulation with any EPW file, although it is recommended to have previously renamed them with the class rename_epw_files().

Let's remove the new output IDFs for clarity purposes:

In [6]:
for i in os.listdir():
    if i.endswith('.idf') and input_idf[0] not in i:
        os.remove(i)

### 1.2 Longer version

Let's double check we only have the initial idf we used in the short version:

In [7]:
input_idf = [i for i in os.listdir() if i.endswith('.idf')]
print(*input_idf, sep='\n')

TestModel.idf

Now, let's do the same, but using the longer version:

In [8]:
from accim.sim import accis
accis.addAccis(
    ScriptType='vrf_mm',
    SupplyAirTempInputMethod='temperature difference',
    Output_keep_existing=False,
    Output_type='standard',
    Output_freqs=['hourly', 'runperiod'],
    Output_gen_dataframe=False,
    EnergyPlus_version='auto',
    TempCtrl='temperature',
    ComfStand=[1, 14],
    CAT=[1, 2, 3, 80, 90],
    CATcoolOffset=0,
    CATheatOffset=0,
    ComfMod=[0, 0.1, 0.2, 0.3, 0.4, 0.5, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3],
    SetpointAcc=100,
    CoolSeasonStart='01/11',
    CoolSeasonEnd='01/03',
    HVACmode=[2],
    VentCtrl=[2],
    MaxTempDiffVOF=20,
    MinTempDiffVOF=1,
    MultiplierVOF=0.2,
    VSToffset=[0],
    MinOToffset=[50],
    MaxWindSpeed=[50],
    ASTtol_steps=0.1,
    ASTtol_start=0.1,
    ASTtol_end_input=0.1,
    confirmGen=True
)

--------------------------------------------------------
Adaptive-Comfort-Control-Implemented Model (ACCIM) v0.8.2
--------------------------------------------------------

This tool allows to apply adaptive setpoint temperatures.
For further information, please read the documentation:
https://accim.readthedocs.io/en/master/
For a visual understanding of the tool, please visit the following jupyter notebooks:
-    Using addAccis() to apply adaptive setpoint temperatures
https://accim.readthedocs.io/en/master/jupyter_notebooks/addAccis/using_addAccis.html
-    Using rename_epw_files() to rename the EPWs for proper data analysis after simulation
https://accim.readthedocs.io/en/master/jupyter_notebooks/rename_epw_files/using_rename_epw_files.html
-    Using runEp() to directly run simulations with EnergyPlus
https://accim.readthedocs.io/en/master/jupyter_notebooks/runEp/using_runEp.html
-    Using the class Table() for data analysis
https://accim.readthedocs.io/en/master/jupyter_notebooks/Table/using_Table.html
-    Full example
https://accim.readthedocs.io/en/master/jupyter_notebooks/full_example_IBPSA/full_example_IBPSA.html

Starting with the process.
Basic input data:
ScriptType is: vrf_mm
Supply Air Temperature Input Method is: temperature difference
Output type is: standard
Output frequencies are:
['hourly', 'runperiod']
Temperature Control method is: temperature

=======================START OF GENERIC IDF FILE GENERATION PROCESS=======================

Starting with file:
TestModel
IDD location is: C:\EnergyPlusV25-1-0\Energy+.idd

The occupied zones in the model TestModel are:
Block1:Zone1
Block1:Zone2
The windows and doors in the model TestModel are:
Block1_Zone2_Wall_3_0_0_0_0_0_Win
Block1_Zone2_Wall_4_0_0_0_0_0_Win
Block1_Zone2_Wall_5_0_0_0_0_0_Win
Block1_Zone1_Wall_2_0_0_0_0_0_Win
Block1_Zone1_Wall_3_0_0_0_0_0_Win
Block1_Zone1_Wall_5_0_0_0_0_0_Win
The zones in the model TestModel are:
Block1_Zone1
Block1_Zone2
The people objects in the model have been amended.
Block1:Zone1 Thermostat has been added
Block1:Zone2 Thermostat has been added
On Schedule already was in the model
TypOperativeTempControlSch Schedule already was in the model
All ZoneHVAC:IdealLoadsAirSystem Heating and Cooling availability schedules has been set to on
On 24/7 Schedule already was in the model
Control type schedule: Always 4 Schedule has been added
Relative humidity setpoint schedule: Always 50.00 Schedule has been added
Heating Fanger comfort setpoint: Always -0.5 Schedule has been added
Cooling Fanger comfort setpoint: Always  0.1 Schedule has been added
Zone CO2 setpoint: Always 900ppm Schedule has been added
Min CO2 concentration: Always 600ppm Schedule has been added
Generic contaminant setpoint: Always 0.5ppm Schedule has been added
Air distribution effectiveness (always 1) Schedule has been added
VRF Heating Cooling (Northern Hemisphere) Schedule has been added
DefaultFanEffRatioCurve Curve:Cubic Object has been added
VRFTUCoolCapFT Curve:Cubic Object has been added
VRFTUHeatCapFT Curve:Cubic Object has been added
VRFCoolCapFTBoundary Curve:Cubic Object has been added
VRFCoolEIRFTBoundary Curve:Cubic Object has been added
CoolingEIRLowPLR Curve:Cubic Object has been added
VRFHeatCapFTBoundary Curve:Cubic Object has been added
VRFHeatEIRFTBoundary Curve:Cubic Object has been added
HeatingEIRLowPLR Curve:Cubic Object has been added
DefaultFanPowerRatioCurve Curve:Exponent Object has been added
DXHtgCoilDefrostEIRFT Curve:Biquadratic Object has been added
VRFCoolCapFT Curve:Biquadratic Object has been added
VRFCoolCapFTHi Curve:Biquadratic Object has been added
VRFCoolEIRFT Curve:Biquadratic Object has been added
VRFCoolEIRFTHi Curve:Biquadratic Object has been added
VRFHeatCapFT Curve:Biquadratic Object has been added
VRFHeatCapFTHi Curve:Biquadratic Object has been added
VRFHeatEIRFT Curve:Biquadratic Object has been added
VRFHeatEIRFTHi Curve:Biquadratic Object has been added
CoolingLengthCorrectionFactor Curve:Biquadratic Object has been added
VRF Piping Correction Factor for Length in Heating Mode Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Energy Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Energy Modifier Curve:Biquadratic Object has been added
VRFACCoolCapFFF Curve:Quadratic Object has been added
CoolingEIRHiPLR Curve:Quadratic Object has been added
VRFCPLFFPLR Curve:Quadratic Object has been added
HeatingEIRHiPLR Curve:Quadratic Object has been added
CoolingCombRatio Curve:Linear Object has been added
HeatingCombRatio Curve:Linear Object has been added
VRF Outdoor Unit_Block1:Zone1 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone2 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone1 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone1 Zone List Object has been added
VRF Outdoor Unit_Block1:Zone2 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone2 Zone List Object has been added
Block1:Zone1 Sizing:Zone Object has been added
Block1:Zone2 Sizing:Zone Object has been added
Block1:Zone1 Design Specification Outdoor Air Object has been added
Block1:Zone2 Design Specification Outdoor Air Object has been added
Block1:Zone1 Design Specification Zone Air Distribution Object has been added
Block1:Zone2 Design Specification Zone Air Distribution Object has been added
Block1:Zone1 Nodelist Objects has been added
Block1:Zone2 Nodelist Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone1 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone2 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Fan:ConstantVolume Object has been added
Block1:Zone2 Fan:ConstantVolume Object has been added
Vent_SP_temp Schedule has been added
AHST_Sch_Block1_Zone2 Schedule has been added
ACST_Sch_Block1_Zone2 Schedule has been added
AHST_Sch_Block1_Zone1 Schedule has been added
ACST_Sch_Block1_Zone1 Schedule has been added
Added - SetComfTemp Program
Added - CountHours_Block1_Zone2 Program
Added - CountHours_Block1_Zone1 Program
Added - SetAppLimits Program
Added - ApplyCAT Program
Added - SetAST_Master Program with 109 lines

Added - 46 per-ComfStand SetAST subprograms
Added - SetAST Program (base program that calls SetAST_Master)
Added - SetASTnoTol Program
Added - InitASTvariables Program
Added - CountHoursNoApp_Block1_Zone2 Program
Added - SetGeoVarBlock1_Zone2 Program
Added - CountHoursNoApp_Block1_Zone1 Program
Added - SetGeoVarBlock1_Zone1 Program
Added - SetInputData Program
Added - SetVOFinputData Program
Added - SetVST Program
Added - ApplyAST_Block1_Zone2 Program
Added - ApplyAST_Block1_Zone1 Program
Added - SetMyVOF_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - Comfort Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature Output Variable
Added - Adaptive Heating Setpoint Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature_No Tolerance Output Variable
Added - Adaptive Heating Setpoint Temperature_No Tolerance Output Variable
[... 298 lines not shown in the documentation ...]
Added Output:Meter for DistrictCooling:Facility (hourly)
Added Output:Meter for Heating:EnergyTransfer (hourly)
Added Output:Meter for Cooling:EnergyTransfer (hourly)
Added Output:Meter for Heating:Electricity (hourly)
Added Output:Meter for Cooling:Electricity (hourly)
Added Output:Meter for EnergyTransfer:HVAC (runperiod)
Added Output:Meter for Electricity:HVAC (runperiod)
Added Output:Meter for DistrictHeating:Facility (runperiod)
Added Output:Meter for DistrictCooling:Facility (runperiod)
Added Output:Meter for Heating:EnergyTransfer (runperiod)
Added Output:Meter for Cooling:EnergyTransfer (runperiod)
Added Output:Meter for Heating:Electricity (runperiod)
Added Output:Meter for Cooling:Electricity (runperiod)
Modified - SimulationControl object: enabled Zone, System, and Plant Sizing Calculations

IDF has been saved
Ending with file:
TestModel

=======================END OF GENERIC IDF FILE GENERATION PROCESS=======================

The following IDFs will not work, and therefore these will be deleted:
None

=======================START OF OUTPUT IDF FILES GENERATION PROCESS=======================

The list of output IDFs is going to be:
TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
And the total number of output IDFs is going to be 36
Generating the following output IDF files:
TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf

=======================END OF OUTPUT IDF FILES GENERATION PROCESS=======================

Let's see what files we do have now in the folder:

In [9]:
os.listdir()

['TestModel.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf',
 'using_addAccis.ipynb',
 '__init__.py']

We can see there are new IDFs, as stated previously in the python console:

In [10]:
output_idfs = [i for i in os.listdir() if not(any(i in j for j in input_idf)) and i.endswith('.idf')]
print(*output_idfs, sep='\n')

TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf

Now, these are ready for simulation with any EPW file, although it is recommended to have previously renamed them with the class rename_epw_files().

Let's remove the new output IDFs for clarity purposes:

In [11]:
for i in os.listdir():
    if i.endswith('.idf') and input_idf[0] not in i:
        os.remove(i)

## 2. Other uses

### 2.1 Storing the ``addAccis()`` class and inspecting the output IDFs

Additionally to just run ``addAccis()`` (i.e. instantiate the class), the user can also store the instance and inspect some variables. So let's store the instance in the variable ``add_accis_instance`` and then we'll take a look what's inside:

In [12]:
from accim.sim import accis
add_accis_instance = accis.addAccis(
    ScriptType='vrf_mm',
    SupplyAirTempInputMethod='temperature difference',
    Output_keep_existing=False,
    Output_type='standard',
    Output_freqs=['hourly', 'runperiod'],
    Output_gen_dataframe=False,
    EnergyPlus_version='auto',
    TempCtrl='temperature',
    ComfStand=[1, 14],
    CAT=[1, 2, 3, 80, 90],
    ComfMod=[0, 0.1, 0.2, 0.3, 0.4, 0.5, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3],
    SetpointAcc=100,
    CoolSeasonStart='01/11',
    CoolSeasonEnd='01/03',
    HVACmode=[2],
    VentCtrl=[2],
    MaxTempDiffVOF=20,
    MinTempDiffVOF=1,
    MultiplierVOF=0.2,
    VSToffset=[0],
    MinOToffset=[50],
    MaxWindSpeed=[50],
    ASTtol_steps=0.1,
    ASTtol_start=0.1,
    ASTtol_end_input=0.1,
    confirmGen=True
)

--------------------------------------------------------
Adaptive-Comfort-Control-Implemented Model (ACCIM) v0.8.2
--------------------------------------------------------

This tool allows to apply adaptive setpoint temperatures.
For further information, please read the documentation:
https://accim.readthedocs.io/en/master/
For a visual understanding of the tool, please visit the following jupyter notebooks:
-    Using addAccis() to apply adaptive setpoint temperatures
https://accim.readthedocs.io/en/master/jupyter_notebooks/addAccis/using_addAccis.html
-    Using rename_epw_files() to rename the EPWs for proper data analysis after simulation
https://accim.readthedocs.io/en/master/jupyter_notebooks/rename_epw_files/using_rename_epw_files.html
-    Using runEp() to directly run simulations with EnergyPlus
https://accim.readthedocs.io/en/master/jupyter_notebooks/runEp/using_runEp.html
-    Using the class Table() for data analysis
https://accim.readthedocs.io/en/master/jupyter_notebooks/Table/using_Table.html
-    Full example
https://accim.readthedocs.io/en/master/jupyter_notebooks/full_example_IBPSA/full_example_IBPSA.html

Starting with the process.
Basic input data:
ScriptType is: vrf_mm
Supply Air Temperature Input Method is: temperature difference
Output type is: standard
Output frequencies are:
['hourly', 'runperiod']
Temperature Control method is: temperature

=======================START OF GENERIC IDF FILE GENERATION PROCESS=======================

Starting with file:
TestModel
IDD location is: C:\EnergyPlusV25-1-0\Energy+.idd

The occupied zones in the model TestModel are:
Block1:Zone1
Block1:Zone2
The windows and doors in the model TestModel are:
Block1_Zone2_Wall_3_0_0_0_0_0_Win
Block1_Zone2_Wall_4_0_0_0_0_0_Win
Block1_Zone2_Wall_5_0_0_0_0_0_Win
Block1_Zone1_Wall_2_0_0_0_0_0_Win
Block1_Zone1_Wall_3_0_0_0_0_0_Win
Block1_Zone1_Wall_5_0_0_0_0_0_Win
The zones in the model TestModel are:
Block1_Zone1
Block1_Zone2
The people objects in the model have been amended.
Block1:Zone1 Thermostat has been added
Block1:Zone2 Thermostat has been added
On Schedule already was in the model
TypOperativeTempControlSch Schedule already was in the model
All ZoneHVAC:IdealLoadsAirSystem Heating and Cooling availability schedules has been set to on
On 24/7 Schedule already was in the model
Control type schedule: Always 4 Schedule has been added
Relative humidity setpoint schedule: Always 50.00 Schedule has been added
Heating Fanger comfort setpoint: Always -0.5 Schedule has been added
Cooling Fanger comfort setpoint: Always  0.1 Schedule has been added
Zone CO2 setpoint: Always 900ppm Schedule has been added
Min CO2 concentration: Always 600ppm Schedule has been added
Generic contaminant setpoint: Always 0.5ppm Schedule has been added
Air distribution effectiveness (always 1) Schedule has been added
VRF Heating Cooling (Northern Hemisphere) Schedule has been added
DefaultFanEffRatioCurve Curve:Cubic Object has been added
VRFTUCoolCapFT Curve:Cubic Object has been added
VRFTUHeatCapFT Curve:Cubic Object has been added
VRFCoolCapFTBoundary Curve:Cubic Object has been added
VRFCoolEIRFTBoundary Curve:Cubic Object has been added
CoolingEIRLowPLR Curve:Cubic Object has been added
VRFHeatCapFTBoundary Curve:Cubic Object has been added
VRFHeatEIRFTBoundary Curve:Cubic Object has been added
HeatingEIRLowPLR Curve:Cubic Object has been added
DefaultFanPowerRatioCurve Curve:Exponent Object has been added
DXHtgCoilDefrostEIRFT Curve:Biquadratic Object has been added
VRFCoolCapFT Curve:Biquadratic Object has been added
VRFCoolCapFTHi Curve:Biquadratic Object has been added
VRFCoolEIRFT Curve:Biquadratic Object has been added
VRFCoolEIRFTHi Curve:Biquadratic Object has been added
VRFHeatCapFT Curve:Biquadratic Object has been added
VRFHeatCapFTHi Curve:Biquadratic Object has been added
VRFHeatEIRFT Curve:Biquadratic Object has been added
VRFHeatEIRFTHi Curve:Biquadratic Object has been added
CoolingLengthCorrectionFactor Curve:Biquadratic Object has been added
VRF Piping Correction Factor for Length in Heating Mode Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Energy Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Energy Modifier Curve:Biquadratic Object has been added
VRFACCoolCapFFF Curve:Quadratic Object has been added
CoolingEIRHiPLR Curve:Quadratic Object has been added
VRFCPLFFPLR Curve:Quadratic Object has been added
HeatingEIRHiPLR Curve:Quadratic Object has been added
CoolingCombRatio Curve:Linear Object has been added
HeatingCombRatio Curve:Linear Object has been added
VRF Outdoor Unit_Block1:Zone1 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone2 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone1 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone1 Zone List Object has been added
VRF Outdoor Unit_Block1:Zone2 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone2 Zone List Object has been added
Block1:Zone1 Sizing:Zone Object has been added
Block1:Zone2 Sizing:Zone Object has been added
Block1:Zone1 Design Specification Outdoor Air Object has been added
Block1:Zone2 Design Specification Outdoor Air Object has been added
Block1:Zone1 Design Specification Zone Air Distribution Object has been added
Block1:Zone2 Design Specification Zone Air Distribution Object has been added
Block1:Zone1 Nodelist Objects has been added
Block1:Zone2 Nodelist Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone1 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone2 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Fan:ConstantVolume Object has been added
Block1:Zone2 Fan:ConstantVolume Object has been added
Vent_SP_temp Schedule has been added
AHST_Sch_Block1_Zone2 Schedule has been added
ACST_Sch_Block1_Zone2 Schedule has been added
AHST_Sch_Block1_Zone1 Schedule has been added
ACST_Sch_Block1_Zone1 Schedule has been added
Added - SetComfTemp Program
Added - CountHours_Block1_Zone2 Program
Added - CountHours_Block1_Zone1 Program
Added - SetAppLimits Program
Added - ApplyCAT Program
Added - SetAST_Master Program with 109 lines

Added - 46 per-ComfStand SetAST subprograms
Added - SetAST Program (base program that calls SetAST_Master)
Added - SetASTnoTol Program
Added - InitASTvariables Program
Added - CountHoursNoApp_Block1_Zone2 Program
Added - SetGeoVarBlock1_Zone2 Program
Added - CountHoursNoApp_Block1_Zone1 Program
Added - SetGeoVarBlock1_Zone1 Program
Added - SetInputData Program
Added - SetVOFinputData Program
Added - SetVST Program
Added - ApplyAST_Block1_Zone2 Program
Added - ApplyAST_Block1_Zone1 Program
Added - SetMyVOF_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - Comfort Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature Output Variable
Added - Adaptive Heating Setpoint Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature_No Tolerance Output Variable
Added - Adaptive Heating Setpoint Temperature_No Tolerance Output Variable
[... 298 lines not shown in the documentation ...]
Added Output:Meter for DistrictCooling:Facility (hourly)
Added Output:Meter for Heating:EnergyTransfer (hourly)
Added Output:Meter for Cooling:EnergyTransfer (hourly)
Added Output:Meter for Heating:Electricity (hourly)
Added Output:Meter for Cooling:Electricity (hourly)
Added Output:Meter for EnergyTransfer:HVAC (runperiod)
Added Output:Meter for Electricity:HVAC (runperiod)
Added Output:Meter for DistrictHeating:Facility (runperiod)
Added Output:Meter for DistrictCooling:Facility (runperiod)
Added Output:Meter for Heating:EnergyTransfer (runperiod)
Added Output:Meter for Cooling:EnergyTransfer (runperiod)
Added Output:Meter for Heating:Electricity (runperiod)
Added Output:Meter for Cooling:Electricity (runperiod)
Modified - SimulationControl object: enabled Zone, System, and Plant Sizing Calculations

IDF has been saved
Ending with file:
TestModel

=======================END OF GENERIC IDF FILE GENERATION PROCESS=======================

The following IDFs will not work, and therefore these will be deleted:
None

=======================START OF OUTPUT IDF FILES GENERATION PROCESS=======================

The list of output IDFs is going to be:
TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
And the total number of output IDFs is going to be 36
Generating the following output IDF files:
TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf

=======================END OF OUTPUT IDF FILES GENERATION PROCESS=======================

Now, let's take a look into the variables within the ``addAccis()`` instance ``add_accis_instance``:

In [13]:
[i for i in dir(add_accis_instance) if '__' not in i]

['arguments',
 'input_idfs',
 'occupied_zones',
 'occupied_zones_original_name',
 'output_idfs',
 'windows_and_doors',
 'windows_and_doors_original_name']

For instance, we can take a look at the arguments we have requested when ``addAccis`` was called:

In [14]:
add_accis_instance.arguments

{'ScriptType': 'vrf_mm',
 'SupplyAirTempInputMethod': 'temperature difference',
 'Output_type': 'standard',
 'Output_freqs': ['hourly', 'runperiod'],
 'Output_keep_existing': False,
 'Output_gen_dataframe': False,
 'Output_take_dataframe': None,
 'EnergyPlus_version': 'auto',
 'TempCtrl': 'temperature',
 'ComfStand': [1, 14],
 'CAT': [1, 2, 3, 80, 90],
 'CATcoolOffset': 0,
 'CATheatOffset': 0,
 'ComfMod': [0, 0.1, 0.2, 0.3, 0.4, 0.5, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3],
 'SetpointAcc': 100,
 'CustAST_ACSTaul': 0,
 'CustAST_ACSTall': 0,
 'CustAST_AHSTaul': 0,
 'CustAST_AHSTall': 0,
 'CustAST_m': 0,
 'CustAST_n': 0,
 'CustAST_ACSToffset': 0,
 'CustAST_AHSToffset': 0,
 'CoolSeasonStart': '01/11',
 'CoolSeasonEnd': '01/03',
 'HVACmode': [2],
 'VentCtrl': [2],
 'MaxTempDiffVOF': 20,
 'MinTempDiffVOF': 1,
 'MultiplierVOF': 0.2,
 'VSToffset': [0],
 'MinOToffset': [50],
 'MaxWindSpeed': [50],
 'ASTtol_start': 0.1,
 'ASTtol_end_input': 0.1,
 'ASTtol_steps': 0.1,
 'NameSuffix': '',
 'verboseMode': True,
 'confirmGen': True}

Also, we can see the list of occupied zones and windows and doors in each model, considering the original names and the new names needed by accim:

In [15]:
add_accis_instance.occupied_zones

{'TestModel': ['Block1_Zone1', 'Block1_Zone2']}

In [16]:
add_accis_instance.occupied_zones_original_name

{'TestModel': ['Block1:Zone1', 'Block1:Zone2']}

In [17]:
add_accis_instance.windows_and_doors

{'TestModel': ['Block1_Zone2_Wall_3_0_0_0_0_0_Win',
  'Block1_Zone2_Wall_4_0_0_0_0_0_Win',
  'Block1_Zone2_Wall_5_0_0_0_0_0_Win',
  'Block1_Zone1_Wall_2_0_0_0_0_0_Win',
  'Block1_Zone1_Wall_3_0_0_0_0_0_Win',
  'Block1_Zone1_Wall_5_0_0_0_0_0_Win']}

In [18]:
add_accis_instance.windows_and_doors_original_name

{'TestModel': ['Block1:Zone2_Wall_3_0_0_0_0_0_Win',
  'Block1:Zone2_Wall_4_0_0_0_0_0_Win',
  'Block1:Zone2_Wall_5_0_0_0_0_0_Win',
  'Block1:Zone1_Wall_2_0_0_0_0_0_Win',
  'Block1:Zone1_Wall_3_0_0_0_0_0_Win',
  'Block1:Zone1_Wall_5_0_0_0_0_0_Win']}

As you can see, these variables are dictionaries following the pattern: ``{'input idf filename': [list]}``

Also, we can inspect both the input and output idf files using eppy. In both cases, the variables ``input_idfs`` and ``output_idfs`` contains a dictionary following the pattern ``{'idf filename': eppy.modeleditor.IDF object}``. For instance, let's take a look at the ``input_idfs`` variable.

In [19]:
add_accis_instance.input_idfs

{'TestModel': <besos.IDF_class.IDF at 0x27a4344e8b0>}

So let's read the eppy.modeleditor.IDF object of the idf TestModel. For instance, let's see which zones are in the IDF by reading it, and if these are the same as previously seen in ``add_accis_instance.occupied_zones_original_name``:

In [20]:
testmodel = add_accis_instance.input_idfs['TestModel']
testmodel.idfobjects['ZONE']

[
Zone,
    Block1:Zone2,             !- Name
    0,                        !- Direction of Relative North
    0,                        !- X Origin
    0,                        !- Y Origin
    0,                        !- Z Origin
    1,                        !- Type
    1,                        !- Multiplier
    ,                         !- Ceiling Height
    126.7064,                 !- Volume
    36.2018,                  !- Floor Area
    TARP,                     !- Zone Inside Convection Algorithm
    ,                         !- Zone Outside Convection Algorithm
    Yes;                      !- Part of Total Floor Area
,
Zone,
    Block1:Zone1,             !- Name
    0,                        !- Direction of Relative North
    0,                        !- X Origin
    0,                        !- Y Origin
    0,                        !- Z Origin
    1,                        !- Type
    1,                        !- Multiplier
    ,                         !- Ceiling Height
    105.3337,                 !- Volume
    30.0953,                  !- Floor Area
    TARP,                     !- Zone Inside Convection Algorithm
    ,                         !- Zone Outside Convection Algorithm
    Yes;                      !- Part of Total Floor Area
]

And we can see these are the same. Also, you can take a look at the variable ``output_idfs``, which is another dictionary similar to ``input_idfs`` but with the output files.

In [21]:
add_accis_instance.output_idfs

{'TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>,
 'TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf': <besos.IDF_class.IDF at 0x27a92344850>}

Let's read the last one. Let's see, for instance, the Schedule:Compact objects for the thermostats:

In [22]:
ast_testmodel = add_accis_instance.output_idfs[
    'TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf'
]
ast_testmodel.idfobjects['ThermostatSetpoint:DualSetpoint']

[
THERMOSTATSETPOINT:DUALSETPOINT,
    Block1:Zone2 Dual SP,     !- Name
    AHST_Sch_Block1_Zone2,    !- Heating Setpoint Temperature Schedule Name
    ACST_Sch_Block1_Zone2;    !- Cooling Setpoint Temperature Schedule Name
,
THERMOSTATSETPOINT:DUALSETPOINT,
    Block1:Zone1 Dual SP,     !- Name
    AHST_Sch_Block1_Zone1,    !- Heating Setpoint Temperature Schedule Name
    ACST_Sch_Block1_Zone1;    !- Cooling Setpoint Temperature Schedule Name
]

And now let's compare this with the input idf:

In [23]:
testmodel.idfobjects['ThermostatSetpoint:DualSetpoint']

[
ThermostatSetpoint:DualSetpoint,
    Dual Setpoint - Zone Block1:Zone2,    !- Name
    Block1:Zone2 Heating Setpoint Schedule,    !- Heating Setpoint Temperature Schedule Name
    Block1:Zone2 Cooling SP Sch;    !- Cooling Setpoint Temperature Schedule Name
,
ThermostatSetpoint:DualSetpoint,
    Dual Setpoint - Zone Block1:Zone1,    !- Name
    Block1:Zone1 Heating Setpoint Schedule,    !- Heating Setpoint Temperature Schedule Name
    Block1:Zone1 Cooling SP Sch;    !- Cooling Setpoint Temperature Schedule Name
]

Therefore, we can confirm the Schedule:Compact objects for output idf stored in variable ``ast_testmodel`` are AHST and ACST, and thus, adaptive setpoint temperatures have been applied. However, this is different in the original idf, stored in variable ``testmodel``, in which setpoint temperatures are static.

For more information about the use of eppy, please refer to the documentation at https://eppy.readthedocs.io/en/latest/ or https://eppy.readthedocs.io/en/latest/Main_Tutorial.html

Let's delete all the output idf files so that we can re-run the notebook.

In [24]:
for i in os.listdir():
    if i.endswith('.idf') and input_idf[0] not in i:
        os.remove(i)

### 2.2 Specifying the outputs in the IDF

#### 2.2.1 Using ``Output_type='custom'``

Imagine you need to perform a large number of simulations, therefore, using ``Output_type='standard'`` would result in a heavy dataset. Using ``Output_type='simplified'`` is not an option, since you need more outputs than just the operative temperature, heating coil heating rate and cooling coil total cooling rate. In that case, you can use ``Output_type='custom'``. If you do so, accim will iterate through the existing reporting frequencies and will show you all the existing Output:Variable objects for that frequency, and then, you'll be asked the following:
- firstly, you'll need to say if you want to remove some object or otherwise keep some and remove all others by entering "remove" or "keep"
- secondly, you'll have to say all Output:Variable objects you want to remove or keep

So let's say we want to keep (therefore, enter **keep**) the following Output:Variable objects (you may not be aware of them, but in that case, you can see the existing objects in the list accim prints), which you'll need to enter separated by semicolon (;):

**Zone Operative Temperature;Adaptive Cooling Setpoint Temperature_No Tolerance;Adaptive Heating Setpoint Temperature_No Tolerance**

Also, in this case, we are going to store the ``addAccis()`` instance in the variable ``add_accis_instance`` (similar to previous section 2.1), so that we can inspect it later.

First of all, let's see the idfs we do have in this path:

In [25]:
from os import listdir
input_idfs = [i for i in listdir() if i.endswith('.idf')]
input_idfs

['TestModel.idf']

Now, we can go for it:

In [26]:
from accim.sim import accis
add_accis_instance = accis.addAccis(
    ScriptType='vrf_mm',
    SupplyAirTempInputMethod='temperature difference',
    Output_keep_existing=False,
    Output_type='custom',
    Output_freqs=['hourly', 'runperiod'],
    Output_gen_dataframe=False,
    EnergyPlus_version='auto',
    TempCtrl='temperature',
    ComfStand=[1, 14],
    CAT=[1, 2, 3, 80, 90],
    ComfMod=[0, 0.1, 0.2, 0.3, 0.4, 0.5, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3],
    SetpointAcc=100,
    CoolSeasonStart='01/11',
    CoolSeasonEnd='01/03',
    HVACmode=[2],
    VentCtrl=[2],
    MaxTempDiffVOF=20,
    MinTempDiffVOF=1,
    MultiplierVOF=0.2,
    VSToffset=[0],
    MinOToffset=[50],
    MaxWindSpeed=[50],
    ASTtol_steps=0.1,
    ASTtol_start=0.1,
    ASTtol_end_input=0.1,
    confirmGen=True
)

--------------------------------------------------------
Adaptive-Comfort-Control-Implemented Model (ACCIM) v0.8.2
--------------------------------------------------------

This tool allows to apply adaptive setpoint temperatures.
For further information, please read the documentation:
https://accim.readthedocs.io/en/master/
For a visual understanding of the tool, please visit the following jupyter notebooks:
-    Using addAccis() to apply adaptive setpoint temperatures
https://accim.readthedocs.io/en/master/jupyter_notebooks/addAccis/using_addAccis.html
-    Using rename_epw_files() to rename the EPWs for proper data analysis after simulation
https://accim.readthedocs.io/en/master/jupyter_notebooks/rename_epw_files/using_rename_epw_files.html
-    Using runEp() to directly run simulations with EnergyPlus
https://accim.readthedocs.io/en/master/jupyter_notebooks/runEp/using_runEp.html
-    Using the class Table() for data analysis
https://accim.readthedocs.io/en/master/jupyter_notebooks/Table/using_Table.html
-    Full example
https://accim.readthedocs.io/en/master/jupyter_notebooks/full_example_IBPSA/full_example_IBPSA.html

Starting with the process.
Basic input data:
ScriptType is: vrf_mm
Supply Air Temperature Input Method is: temperature difference
Output type is: custom
Output frequencies are:
['hourly', 'runperiod']
Temperature Control method is: temperature

=======================START OF GENERIC IDF FILE GENERATION PROCESS=======================

Starting with file:
TestModel
IDD location is: C:\EnergyPlusV25-1-0\Energy+.idd

The occupied zones in the model TestModel are:
Block1:Zone1
Block1:Zone2
The windows and doors in the model TestModel are:
Block1_Zone2_Wall_3_0_0_0_0_0_Win
Block1_Zone2_Wall_4_0_0_0_0_0_Win
Block1_Zone2_Wall_5_0_0_0_0_0_Win
Block1_Zone1_Wall_2_0_0_0_0_0_Win
Block1_Zone1_Wall_3_0_0_0_0_0_Win
Block1_Zone1_Wall_5_0_0_0_0_0_Win
The zones in the model TestModel are:
Block1_Zone1
Block1_Zone2
The people objects in the model have been amended.
Block1:Zone1 Thermostat has been added
Block1:Zone2 Thermostat has been added
On Schedule already was in the model
TypOperativeTempControlSch Schedule already was in the model
All ZoneHVAC:IdealLoadsAirSystem Heating and Cooling availability schedules has been set to on
On 24/7 Schedule already was in the model
Control type schedule: Always 4 Schedule has been added
Relative humidity setpoint schedule: Always 50.00 Schedule has been added
Heating Fanger comfort setpoint: Always -0.5 Schedule has been added
Cooling Fanger comfort setpoint: Always  0.1 Schedule has been added
Zone CO2 setpoint: Always 900ppm Schedule has been added
Min CO2 concentration: Always 600ppm Schedule has been added
Generic contaminant setpoint: Always 0.5ppm Schedule has been added
Air distribution effectiveness (always 1) Schedule has been added
VRF Heating Cooling (Northern Hemisphere) Schedule has been added
DefaultFanEffRatioCurve Curve:Cubic Object has been added
VRFTUCoolCapFT Curve:Cubic Object has been added
VRFTUHeatCapFT Curve:Cubic Object has been added
VRFCoolCapFTBoundary Curve:Cubic Object has been added
VRFCoolEIRFTBoundary Curve:Cubic Object has been added
CoolingEIRLowPLR Curve:Cubic Object has been added
VRFHeatCapFTBoundary Curve:Cubic Object has been added
VRFHeatEIRFTBoundary Curve:Cubic Object has been added
HeatingEIRLowPLR Curve:Cubic Object has been added
DefaultFanPowerRatioCurve Curve:Exponent Object has been added
DXHtgCoilDefrostEIRFT Curve:Biquadratic Object has been added
VRFCoolCapFT Curve:Biquadratic Object has been added
VRFCoolCapFTHi Curve:Biquadratic Object has been added
VRFCoolEIRFT Curve:Biquadratic Object has been added
VRFCoolEIRFTHi Curve:Biquadratic Object has been added
VRFHeatCapFT Curve:Biquadratic Object has been added
VRFHeatCapFTHi Curve:Biquadratic Object has been added
VRFHeatEIRFT Curve:Biquadratic Object has been added
VRFHeatEIRFTHi Curve:Biquadratic Object has been added
CoolingLengthCorrectionFactor Curve:Biquadratic Object has been added
VRF Piping Correction Factor for Length in Heating Mode Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Energy Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Energy Modifier Curve:Biquadratic Object has been added
VRFACCoolCapFFF Curve:Quadratic Object has been added
CoolingEIRHiPLR Curve:Quadratic Object has been added
VRFCPLFFPLR Curve:Quadratic Object has been added
HeatingEIRHiPLR Curve:Quadratic Object has been added
CoolingCombRatio Curve:Linear Object has been added
HeatingCombRatio Curve:Linear Object has been added
VRF Outdoor Unit_Block1:Zone1 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone2 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone1 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone1 Zone List Object has been added
VRF Outdoor Unit_Block1:Zone2 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone2 Zone List Object has been added
Block1:Zone1 Sizing:Zone Object has been added
Block1:Zone2 Sizing:Zone Object has been added
Block1:Zone1 Design Specification Outdoor Air Object has been added
Block1:Zone2 Design Specification Outdoor Air Object has been added
Block1:Zone1 Design Specification Zone Air Distribution Object has been added
Block1:Zone2 Design Specification Zone Air Distribution Object has been added
Block1:Zone1 Nodelist Objects has been added
Block1:Zone2 Nodelist Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone1 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone2 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Fan:ConstantVolume Object has been added
Block1:Zone2 Fan:ConstantVolume Object has been added
Vent_SP_temp Schedule has been added
AHST_Sch_Block1_Zone2 Schedule has been added
ACST_Sch_Block1_Zone2 Schedule has been added
AHST_Sch_Block1_Zone1 Schedule has been added
ACST_Sch_Block1_Zone1 Schedule has been added
Added - SetComfTemp Program
Added - CountHours_Block1_Zone2 Program
Added - CountHours_Block1_Zone1 Program
Added - SetAppLimits Program
Added - ApplyCAT Program
Added - SetAST_Master Program with 109 lines

Added - 46 per-ComfStand SetAST subprograms
Added - SetAST Program (base program that calls SetAST_Master)
Added - SetASTnoTol Program
Added - InitASTvariables Program
Added - CountHoursNoApp_Block1_Zone2 Program
Added - SetGeoVarBlock1_Zone2 Program
Added - CountHoursNoApp_Block1_Zone1 Program
Added - SetGeoVarBlock1_Zone1 Program
Added - SetInputData Program
Added - SetVOFinputData Program
Added - SetVST Program
Added - ApplyAST_Block1_Zone2 Program
Added - ApplyAST_Block1_Zone1 Program
Added - SetMyVOF_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - Comfort Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature Output Variable
Added - Adaptive Heating Setpoint Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature_No Tolerance Output Variable
Added - Adaptive Heating Setpoint Temperature_No Tolerance Output Variable
[... 374 lines not shown in the documentation ...]
Facility Total HVAC Electric Demand Power
Facility Total HVAC Electricity Demand Rate
AFN Surface Venting Window or Door Opening Factor
AFN Zone Infiltration Air Change Rate
AFN Zone Infiltration Volume
AFN Zone Ventilation Air Change Rate
AFN Zone Ventilation Volume
Zone Ventilation Standard Density Air Change Rate
Site Outdoor Air Drybulb Temperature
Site Wind Speed
Site Outdoor Air Relative Humidity
Schedule Value
VRF Heat Pump Cooling Electricity Energy
VRF Heat Pump Heating Electricity Energy

Do you want to remove some input or keep it and remove all others? Please enter remove or keep:keep
Please enter these outputs (which must be contained in the list above) separated by semicolon (;): Zone Operative Temperature;Adaptive Cooling Setpoint Temperature_No Tolerance;Adaptive Heating Setpoint Temperature_No Tolerance

The current existing outputs for Runperiod Frequency are:
Comfort Temperature
Adaptive Cooling Setpoint Temperature
Adaptive Heating Setpoint Temperature
Adaptive Cooling Setpoint Temperature_No Tolerance
Adaptive Heating Setpoint Temperature_No Tolerance
z_test_ComfStand
z_test_ACSTaul
z_test_ACSTall
z_test_AHSTaul
z_test_AHSTall
z_test_CAT
z_test_ACSToffset
z_test_AHSToffset
z_test_ComfMod
z_test_ACSTtol
z_test_SetpointAcc
z_test_CustAST_m
z_test_CustAST_n
z_test_AHSTtol
Ventilation Setpoint Temperature
Minimum Outdoor Temperature for ventilation
Minimum Outdoor Temperature Difference for ventilation
Maximum Outdoor Temperature Difference for ventilation
Multiplier for Ventilation Opening Factor
Comfortable Hours_No Applicability_Block1_Zone2
Comfortable Hours_No Applicability_Block1_Zone1
Comfortable Hours_Applicability_Block1_Zone2
Comfortable Hours_Applicability_Block1_Zone1
Occupied Comfortable Hours_No Applicability_Block1_Zone2
Occupied Comfortable Hours_No Applicability_Block1_Zone1
Occupied Discomfortable Hours_No Applicability_Block1_Zone2
Occupied Discomfortable Hours_No Applicability_Block1_Zone1
Occupied Hours_Block1_Zone2
Occupied Hours_Block1_Zone1
Discomfortable Applicable Hot Hours_Block1_Zone2
Discomfortable Applicable Hot Hours_Block1_Zone1
Discomfortable Applicable Cold Hours_Block1_Zone2
Discomfortable Applicable Cold Hours_Block1_Zone1
Discomfortable Non Applicable Hot Hours_Block1_Zone2
Discomfortable Non Applicable Hot Hours_Block1_Zone1
Discomfortable Non Applicable Cold Hours_Block1_Zone2
Discomfortable Non Applicable Cold Hours_Block1_Zone1
Zone Floor Area_Block1_Zone2
Zone Floor Area_Block1_Zone1
Zone Air Volume_Block1_Zone2
Zone Air Volume_Block1_Zone1
People Occupant Count_Block1_Zone2
People Occupant Count_Block1_Zone1
Ventilation Hours_Block1_Zone2
Ventilation Hours_Block1_Zone1
Zone Thermostat Operative Temperature
Zone Thermostat Air Temperature
Zone Operative Temperature
Zone Thermal Comfort CEN 15251 Adaptive Model Running Average Outdoor Air Temperature
Zone Thermal Comfort ASHRAE 55 Adaptive Model Running Average Outdoor Air Temperature
Cooling Coil Total Cooling Rate
Heating Coil Heating Rate
Facility Total HVAC Electric Demand Power
Facility Total HVAC Electricity Demand Rate
AFN Surface Venting Window or Door Opening Factor
AFN Zone Infiltration Air Change Rate
AFN Zone Infiltration Volume
AFN Zone Ventilation Air Change Rate
AFN Zone Ventilation Volume
Zone Ventilation Standard Density Air Change Rate
Site Outdoor Air Drybulb Temperature
Site Wind Speed
Site Outdoor Air Relative Humidity
Schedule Value
VRF Heat Pump Cooling Electricity Energy
VRF Heat Pump Heating Electricity Energy
Do you want to remove some input or keep it and remove all others? Please enter remove or keep:keep
Please enter these outputs (which must be contained in the list above) separated by semicolon (;): Zone Operative Temperature;Adaptive Cooling Setpoint Temperature_No Tolerance;Adaptive Heating Setpoint Temperature_No Tolerance
Modified - SimulationControl object: enabled Zone, System, and Plant Sizing Calculations

IDF has been saved
Ending with file:
TestModel

=======================END OF GENERIC IDF FILE GENERATION PROCESS=======================

The following IDFs will not work, and therefore these will be deleted:
None

=======================START OF OUTPUT IDF FILES GENERATION PROCESS=======================

The list of output IDFs is going to be:
TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
And the total number of output IDFs is going to be 36
Generating the following output IDF files:
TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf

=======================END OF OUTPUT IDF FILES GENERATION PROCESS=======================

Now, let's inspect the Output:Variable objects in both the input idf and any of the output idfs, for instance, the first one.

In [27]:
input_testmodel = add_accis_instance.input_idfs['TestModel']
input_testmodel.idfobjects['Output:Variable']

[]

We can see there is no Output:Variable object in the input idf. Now let's see some output idf.

In [28]:
output_testmodel = add_accis_instance.output_idfs[
    'TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf'
]
output_testmodel.idfobjects['Output:Variable']

[
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Adaptive Cooling Setpoint Temperature_No Tolerance,    !- Variable Name
    Hourly,                   !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Adaptive Heating Setpoint Temperature_No Tolerance,    !- Variable Name
    Hourly,                   !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Zone Operative Temperature,    !- Variable Name
    Hourly,                   !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Adaptive Cooling Setpoint Temperature_No Tolerance,    !- Variable Name
    Runperiod,                !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Adaptive Heating Setpoint Temperature_No Tolerance,    !- Variable Name
    Runperiod,                !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Zone Operative Temperature,    !- Variable Name
    Runperiod,                !- Reporting Frequency
    ;                         !- Schedule Name
]

We can see in this case 6 Output:Variable objects, which are the ones we previously requested:
- Zone Operative Temperature
- Adaptive Cooling Setpoint Temperature_No Tolerance
- Adaptive Heating Setpoint Temperature_No Tolerance

in both Hourly and Runperiod Reporting Frequencies.

As usual, let's remove all the output idfs, so that we can re-run the notebook.

In [29]:
for i in os.listdir():
    if i.endswith('.idf') and input_idf[0] not in i:
        os.remove(i)

#### 2.2.2 Using ``Output_gen_dataframe`` and ``Output_take_dataframe``

Similar to section 2.2.1, imagine you need to perform a large number of simulations. Therefore, using Output_type='standard' would result in a heavy dataset. Using Output_type='simplified' is not an option, since you need more outputs than just the operative temperature, heating coil heating rate and cooling coil total cooling rate. In that case, you can use ``Output_gen_dataframe`` and ``Output_take_dataframe``.

First of all, let's see the idfs we do have in this path:

In [30]:
from os import listdir
input_idfs = [i for i in listdir() if i.endswith('.idf')]
input_idfs

['TestModel.idf']

Now, we can go for it. Let's apply the adaptive setpoint temperatures. We want to see what outputs we would have if we run this script, therefore, we need to specify ``Output_gen_dataframe=True``. Since we don't want to generate the output idfs yet, in this case let's specify ``confirmGen=False``.

In [31]:
from accim.sim import accis
add_accis_instance = accis.addAccis(
    ScriptType='vrf_mm',
    SupplyAirTempInputMethod='temperature difference',
    Output_keep_existing=False,
    Output_type='standard',
    Output_freqs=['hourly', 'runperiod'],
    Output_gen_dataframe=True,
    EnergyPlus_version='auto',
    TempCtrl='temperature',
    ComfStand=[1, 14],
    CAT=[1, 2, 3, 80, 90],
    ComfMod=[0, 0.1, 0.2, 0.3, 0.4, 0.5, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3],
    SetpointAcc=100,
    CoolSeasonStart='01/11',
    CoolSeasonEnd='01/03',
    HVACmode=[2],
    VentCtrl=[2],
    MaxTempDiffVOF=20,
    MinTempDiffVOF=1,
    MultiplierVOF=0.2,
    VSToffset=[0],
    MinOToffset=[50],
    MaxWindSpeed=[50],
    ASTtol_steps=0.1,
    ASTtol_start=0.1,
    ASTtol_end_input=0.1,
    confirmGen=False
)

--------------------------------------------------------
Adaptive-Comfort-Control-Implemented Model (ACCIM) v0.8.2
--------------------------------------------------------

This tool allows to apply adaptive setpoint temperatures.
For further information, please read the documentation:
https://accim.readthedocs.io/en/master/
For a visual understanding of the tool, please visit the following jupyter notebooks:
-    Using addAccis() to apply adaptive setpoint temperatures
https://accim.readthedocs.io/en/master/jupyter_notebooks/addAccis/using_addAccis.html
-    Using rename_epw_files() to rename the EPWs for proper data analysis after simulation
https://accim.readthedocs.io/en/master/jupyter_notebooks/rename_epw_files/using_rename_epw_files.html
-    Using runEp() to directly run simulations with EnergyPlus
https://accim.readthedocs.io/en/master/jupyter_notebooks/runEp/using_runEp.html
-    Using the class Table() for data analysis
https://accim.readthedocs.io/en/master/jupyter_notebooks/Table/using_Table.html
-    Full example
https://accim.readthedocs.io/en/master/jupyter_notebooks/full_example_IBPSA/full_example_IBPSA.html

Starting with the process.
Basic input data:
ScriptType is: vrf_mm
Supply Air Temperature Input Method is: temperature difference
Output type is: standard
Output frequencies are:
['hourly', 'runperiod']
Temperature Control method is: temperature

=======================START OF GENERIC IDF FILE GENERATION PROCESS=======================

Starting with file:
TestModel
IDD location is: C:\EnergyPlusV25-1-0\Energy+.idd

The occupied zones in the model TestModel are:
Block1:Zone1
Block1:Zone2
The windows and doors in the model TestModel are:
Block1_Zone2_Wall_3_0_0_0_0_0_Win
Block1_Zone2_Wall_4_0_0_0_0_0_Win
Block1_Zone2_Wall_5_0_0_0_0_0_Win
Block1_Zone1_Wall_2_0_0_0_0_0_Win
Block1_Zone1_Wall_3_0_0_0_0_0_Win
Block1_Zone1_Wall_5_0_0_0_0_0_Win
The zones in the model TestModel are:
Block1_Zone1
Block1_Zone2
The people objects in the model have been amended.
Block1:Zone1 Thermostat has been added
Block1:Zone2 Thermostat has been added
On Schedule already was in the model
TypOperativeTempControlSch Schedule already was in the model
All ZoneHVAC:IdealLoadsAirSystem Heating and Cooling availability schedules has been set to on
On 24/7 Schedule already was in the model
Control type schedule: Always 4 Schedule has been added
Relative humidity setpoint schedule: Always 50.00 Schedule has been added
Heating Fanger comfort setpoint: Always -0.5 Schedule has been added
Cooling Fanger comfort setpoint: Always  0.1 Schedule has been added
Zone CO2 setpoint: Always 900ppm Schedule has been added
Min CO2 concentration: Always 600ppm Schedule has been added
Generic contaminant setpoint: Always 0.5ppm Schedule has been added
Air distribution effectiveness (always 1) Schedule has been added
VRF Heating Cooling (Northern Hemisphere) Schedule has been added
DefaultFanEffRatioCurve Curve:Cubic Object has been added
VRFTUCoolCapFT Curve:Cubic Object has been added
VRFTUHeatCapFT Curve:Cubic Object has been added
VRFCoolCapFTBoundary Curve:Cubic Object has been added
VRFCoolEIRFTBoundary Curve:Cubic Object has been added
CoolingEIRLowPLR Curve:Cubic Object has been added
VRFHeatCapFTBoundary Curve:Cubic Object has been added
VRFHeatEIRFTBoundary Curve:Cubic Object has been added
HeatingEIRLowPLR Curve:Cubic Object has been added
DefaultFanPowerRatioCurve Curve:Exponent Object has been added
DXHtgCoilDefrostEIRFT Curve:Biquadratic Object has been added
VRFCoolCapFT Curve:Biquadratic Object has been added
VRFCoolCapFTHi Curve:Biquadratic Object has been added
VRFCoolEIRFT Curve:Biquadratic Object has been added
VRFCoolEIRFTHi Curve:Biquadratic Object has been added
VRFHeatCapFT Curve:Biquadratic Object has been added
VRFHeatCapFTHi Curve:Biquadratic Object has been added
VRFHeatEIRFT Curve:Biquadratic Object has been added
VRFHeatEIRFTHi Curve:Biquadratic Object has been added
CoolingLengthCorrectionFactor Curve:Biquadratic Object has been added
VRF Piping Correction Factor for Length in Heating Mode Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Energy Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Energy Modifier Curve:Biquadratic Object has been added
VRFACCoolCapFFF Curve:Quadratic Object has been added
CoolingEIRHiPLR Curve:Quadratic Object has been added
VRFCPLFFPLR Curve:Quadratic Object has been added
HeatingEIRHiPLR Curve:Quadratic Object has been added
CoolingCombRatio Curve:Linear Object has been added
HeatingCombRatio Curve:Linear Object has been added
VRF Outdoor Unit_Block1:Zone1 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone2 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone1 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone1 Zone List Object has been added
VRF Outdoor Unit_Block1:Zone2 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone2 Zone List Object has been added
Block1:Zone1 Sizing:Zone Object has been added
Block1:Zone2 Sizing:Zone Object has been added
Block1:Zone1 Design Specification Outdoor Air Object has been added
Block1:Zone2 Design Specification Outdoor Air Object has been added
Block1:Zone1 Design Specification Zone Air Distribution Object has been added
Block1:Zone2 Design Specification Zone Air Distribution Object has been added
Block1:Zone1 Nodelist Objects has been added
Block1:Zone2 Nodelist Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone1 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone2 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Fan:ConstantVolume Object has been added
Block1:Zone2 Fan:ConstantVolume Object has been added
Vent_SP_temp Schedule has been added
AHST_Sch_Block1_Zone2 Schedule has been added
ACST_Sch_Block1_Zone2 Schedule has been added
AHST_Sch_Block1_Zone1 Schedule has been added
ACST_Sch_Block1_Zone1 Schedule has been added
Added - SetComfTemp Program
Added - CountHours_Block1_Zone2 Program
Added - CountHours_Block1_Zone1 Program
Added - SetAppLimits Program
Added - ApplyCAT Program
Added - SetAST_Master Program with 109 lines

Added - 46 per-ComfStand SetAST subprograms
Added - SetAST Program (base program that calls SetAST_Master)
Added - SetASTnoTol Program
Added - InitASTvariables Program
Added - CountHoursNoApp_Block1_Zone2 Program
Added - SetGeoVarBlock1_Zone2 Program
Added - CountHoursNoApp_Block1_Zone1 Program
Added - SetGeoVarBlock1_Zone1 Program
Added - SetInputData Program
Added - SetVOFinputData Program
Added - SetVST Program
Added - ApplyAST_Block1_Zone2 Program
Added - ApplyAST_Block1_Zone1 Program
Added - SetMyVOF_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - Comfort Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature Output Variable
Added - Adaptive Heating Setpoint Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature_No Tolerance Output Variable
Added - Adaptive Heating Setpoint Temperature_No Tolerance Output Variable
[... 298 lines not shown in the documentation ...]
Added Output:Meter for DistrictCooling:Facility (hourly)
Added Output:Meter for Heating:EnergyTransfer (hourly)
Added Output:Meter for Cooling:EnergyTransfer (hourly)
Added Output:Meter for Heating:Electricity (hourly)
Added Output:Meter for Cooling:Electricity (hourly)
Added Output:Meter for EnergyTransfer:HVAC (runperiod)
Added Output:Meter for Electricity:HVAC (runperiod)
Added Output:Meter for DistrictHeating:Facility (runperiod)
Added Output:Meter for DistrictCooling:Facility (runperiod)
Added Output:Meter for Heating:EnergyTransfer (runperiod)
Added Output:Meter for Cooling:EnergyTransfer (runperiod)
Added Output:Meter for Heating:Electricity (runperiod)
Added Output:Meter for Cooling:Electricity (runperiod)
Modified - SimulationControl object: enabled Zone, System, and Plant Sizing Calculations

IDF has been saved
Ending with file:
TestModel

=======================END OF GENERIC IDF FILE GENERATION PROCESS=======================

The following IDFs will not work, and therefore these will be deleted:
None

=======================START OF OUTPUT IDF FILES GENERATION PROCESS=======================

The list of output IDFs is going to be:
TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
And the total number of output IDFs is going to be 36
IDF generation has been shut down

=======================END OF OUTPUT IDF FILES GENERATION PROCESS=======================

We can see no output idf has been generated:

In [32]:
[i for i in listdir() if i.endswith('.idf')]

['TestModel.idf']

However, in this case, there is a variable within ``add_accis_instance`` named ``df_outputs``, which is a pandas DataFrame that contains all Output:Variable objects. Let's take a look:

In [33]:
add_accis_instance.df_outputs

,file,key_value,variable_name,reporting_frequency,schedule_name
0,TestModel,*,Comfort Temperature,Hourly,
1,TestModel,*,Adaptive Cooling Setpoint Temperature,Hourly,
2,TestModel,*,Adaptive Heating Setpoint Temperature,Hourly,
3,TestModel,*,Adaptive Cooling Setpoint Temperature_No Toler...,Hourly,
4,TestModel,*,Adaptive Heating Setpoint Temperature_No Toler...,Hourly,
...,...,...,...,...,...
151,TestModel,*,VRF Heat Pump Heating Electricity Energy,Runperiod,
152,TestModel,Block1_Zone1 VRF Indoor Unit DX Cooling Coil,Cooling Coil Total Cooling Rate,Runperiod,
153,TestModel,Block1_Zone1 VRF Indoor Unit DX Heating Coil,Heating Coil Heating Rate,Runperiod,
154,TestModel,Block1_Zone2 VRF Indoor Unit DX Cooling Coil,Cooling Coil Total Cooling Rate,Runperiod,
155,TestModel,Block1_Zone2 VRF Indoor Unit DX Heating Coil,Heating Coil Heating Rate,Runperiod,

Now, let's save it in a new variable, and let's filter it to keep only the Output:Variable objects we need.

In [34]:
df_outputs_in = add_accis_instance.df_outputs
df_outputs_in = df_outputs_in[
    (
        df_outputs_in['variable_name'].str.contains('Zone Operative Temperature')
        |
        df_outputs_in['variable_name'].str.contains('Adaptive Cooling Setpoint Temperature_No Tolerance')
        |
        df_outputs_in['variable_name'].str.contains('Adaptive Heating Setpoint Temperature_No Tolerance')
    )
]
df_outputs_in

,file,key_value,variable_name,reporting_frequency,schedule_name
3,TestModel,*,Adaptive Cooling Setpoint Temperature_No Toler...,Hourly,
4,TestModel,*,Adaptive Heating Setpoint Temperature_No Toler...,Hourly,
52,TestModel,*,Zone Operative Temperature,Hourly,
81,TestModel,*,Adaptive Cooling Setpoint Temperature_No Toler...,Runperiod,
82,TestModel,*,Adaptive Heating Setpoint Temperature_No Toler...,Runperiod,
130,TestModel,*,Zone Operative Temperature,Runperiod,

Now, we can run again ``addAccis``, specifying ``Output_gen_dataframe=False``, entering the pandas DataFrame instance ``df_outputs_in`` we just filtered in the argument ``Output_take_dataframe``, and specifying ``confirmGen=True``, since now we're ready to apply the adaptive setpoints.

In [35]:
from accim.sim import accis
add_accis_instance = accis.addAccis(
    ScriptType='vrf_mm',
    SupplyAirTempInputMethod='temperature difference',
    Output_keep_existing=False,
    Output_type='standard',
    Output_freqs=['hourly', 'runperiod'],
    Output_gen_dataframe=False,
    Output_take_dataframe=df_outputs_in,
    EnergyPlus_version='auto',
    TempCtrl='temperature',
    ComfStand=[1, 14],
    CAT=[1, 2, 3, 80, 90],
    ComfMod=[0, 0.1, 0.2, 0.3, 0.4, 0.5, 1, 1.1, 1.2, 1.3, 1.4, 1.5, 2, 3],
    SetpointAcc=100,
    CoolSeasonStart='01/11',
    CoolSeasonEnd='01/03',
    HVACmode=[2],
    VentCtrl=[2],
    MaxTempDiffVOF=20,
    MinTempDiffVOF=1,
    MultiplierVOF=0.2,
    VSToffset=[0],
    MinOToffset=[50],
    MaxWindSpeed=[50],
    ASTtol_steps=0.1,
    ASTtol_start=0.1,
    ASTtol_end_input=0.1,
    confirmGen=True
)

--------------------------------------------------------
Adaptive-Comfort-Control-Implemented Model (ACCIM) v0.8.2
--------------------------------------------------------

This tool allows to apply adaptive setpoint temperatures.
For further information, please read the documentation:
https://accim.readthedocs.io/en/master/
For a visual understanding of the tool, please visit the following jupyter notebooks:
-    Using addAccis() to apply adaptive setpoint temperatures
https://accim.readthedocs.io/en/master/jupyter_notebooks/addAccis/using_addAccis.html
-    Using rename_epw_files() to rename the EPWs for proper data analysis after simulation
https://accim.readthedocs.io/en/master/jupyter_notebooks/rename_epw_files/using_rename_epw_files.html
-    Using runEp() to directly run simulations with EnergyPlus
https://accim.readthedocs.io/en/master/jupyter_notebooks/runEp/using_runEp.html
-    Using the class Table() for data analysis
https://accim.readthedocs.io/en/master/jupyter_notebooks/Table/using_Table.html
-    Full example
https://accim.readthedocs.io/en/master/jupyter_notebooks/full_example_IBPSA/full_example_IBPSA.html

Starting with the process.
Basic input data:
ScriptType is: vrf_mm
Supply Air Temperature Input Method is: temperature difference
Output type is: standard
Output frequencies are:
['hourly', 'runperiod']
Temperature Control method is: temperature

=======================START OF GENERIC IDF FILE GENERATION PROCESS=======================

Starting with file:
TestModel
IDD location is: C:\EnergyPlusV25-1-0\Energy+.idd

The occupied zones in the model TestModel are:
Block1:Zone1
Block1:Zone2
The windows and doors in the model TestModel are:
Block1_Zone2_Wall_3_0_0_0_0_0_Win
Block1_Zone2_Wall_4_0_0_0_0_0_Win
Block1_Zone2_Wall_5_0_0_0_0_0_Win
Block1_Zone1_Wall_2_0_0_0_0_0_Win
Block1_Zone1_Wall_3_0_0_0_0_0_Win
Block1_Zone1_Wall_5_0_0_0_0_0_Win
The zones in the model TestModel are:
Block1_Zone1
Block1_Zone2
The people objects in the model have been amended.
Block1:Zone1 Thermostat has been added
Block1:Zone2 Thermostat has been added
On Schedule already was in the model
TypOperativeTempControlSch Schedule already was in the model
All ZoneHVAC:IdealLoadsAirSystem Heating and Cooling availability schedules has been set to on
On 24/7 Schedule already was in the model
Control type schedule: Always 4 Schedule has been added
Relative humidity setpoint schedule: Always 50.00 Schedule has been added
Heating Fanger comfort setpoint: Always -0.5 Schedule has been added
Cooling Fanger comfort setpoint: Always  0.1 Schedule has been added
Zone CO2 setpoint: Always 900ppm Schedule has been added
Min CO2 concentration: Always 600ppm Schedule has been added
Generic contaminant setpoint: Always 0.5ppm Schedule has been added
Air distribution effectiveness (always 1) Schedule has been added
VRF Heating Cooling (Northern Hemisphere) Schedule has been added
DefaultFanEffRatioCurve Curve:Cubic Object has been added
VRFTUCoolCapFT Curve:Cubic Object has been added
VRFTUHeatCapFT Curve:Cubic Object has been added
VRFCoolCapFTBoundary Curve:Cubic Object has been added
VRFCoolEIRFTBoundary Curve:Cubic Object has been added
CoolingEIRLowPLR Curve:Cubic Object has been added
VRFHeatCapFTBoundary Curve:Cubic Object has been added
VRFHeatEIRFTBoundary Curve:Cubic Object has been added
HeatingEIRLowPLR Curve:Cubic Object has been added
DefaultFanPowerRatioCurve Curve:Exponent Object has been added
DXHtgCoilDefrostEIRFT Curve:Biquadratic Object has been added
VRFCoolCapFT Curve:Biquadratic Object has been added
VRFCoolCapFTHi Curve:Biquadratic Object has been added
VRFCoolEIRFT Curve:Biquadratic Object has been added
VRFCoolEIRFTHi Curve:Biquadratic Object has been added
VRFHeatCapFT Curve:Biquadratic Object has been added
VRFHeatCapFTHi Curve:Biquadratic Object has been added
VRFHeatEIRFT Curve:Biquadratic Object has been added
VRFHeatEIRFTHi Curve:Biquadratic Object has been added
CoolingLengthCorrectionFactor Curve:Biquadratic Object has been added
VRF Piping Correction Factor for Length in Heating Mode Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Cooling Energy Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Capacity Modifier Curve:Biquadratic Object has been added
VRF Heat Recovery Heating Energy Modifier Curve:Biquadratic Object has been added
VRFACCoolCapFFF Curve:Quadratic Object has been added
CoolingEIRHiPLR Curve:Quadratic Object has been added
VRFCPLFFPLR Curve:Quadratic Object has been added
HeatingEIRHiPLR Curve:Quadratic Object has been added
CoolingCombRatio Curve:Linear Object has been added
HeatingCombRatio Curve:Linear Object has been added
VRF Outdoor Unit_Block1:Zone1 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone2 AirConditioner:VariableRefrigerantFlow Object has been added
VRF Outdoor Unit_Block1:Zone1 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone1 Zone List Object has been added
VRF Outdoor Unit_Block1:Zone2 Outdoor Air Node Object has been added
VRF Outdoor Unit_Block1:Zone2 Zone List Object has been added
Block1:Zone1 Sizing:Zone Object has been added
Block1:Zone2 Sizing:Zone Object has been added
Block1:Zone1 Design Specification Outdoor Air Object has been added
Block1:Zone2 Design Specification Outdoor Air Object has been added
Block1:Zone1 Design Specification Zone Air Distribution Object has been added
Block1:Zone2 Design Specification Zone Air Distribution Object has been added
Block1:Zone1 Nodelist Objects has been added
Block1:Zone2 Nodelist Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentConnections Objects has been added
Block1:Zone1 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone2 ZoneHVAC:EquipmentList Objects has been added
Block1:Zone1 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone2 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Cooling:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone2 Coil:Heating:DX:VariableRefrigerantFlow Object has been added
Block1:Zone1 Fan:ConstantVolume Object has been added
Block1:Zone2 Fan:ConstantVolume Object has been added
Vent_SP_temp Schedule has been added
AHST_Sch_Block1_Zone2 Schedule has been added
ACST_Sch_Block1_Zone2 Schedule has been added
AHST_Sch_Block1_Zone1 Schedule has been added
ACST_Sch_Block1_Zone1 Schedule has been added
Added - SetComfTemp Program
Added - CountHours_Block1_Zone2 Program
Added - CountHours_Block1_Zone1 Program
Added - SetAppLimits Program
Added - ApplyCAT Program
Added - SetAST_Master Program with 109 lines

Added - 46 per-ComfStand SetAST subprograms
Added - SetAST Program (base program that calls SetAST_Master)
Added - SetASTnoTol Program
Added - InitASTvariables Program
Added - CountHoursNoApp_Block1_Zone2 Program
Added - SetGeoVarBlock1_Zone2 Program
Added - CountHoursNoApp_Block1_Zone1 Program
Added - SetGeoVarBlock1_Zone1 Program
Added - SetInputData Program
Added - SetVOFinputData Program
Added - SetVST Program
Added - ApplyAST_Block1_Zone2 Program
Added - ApplyAST_Block1_Zone1 Program
Added - SetMyVOF_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_4_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone2_Wall_5_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_2_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_3_0_0_0_0_0_Win Program
Added - SetMyVOF_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - SetWindowOperation_Block1_Zone1_Wall_5_0_0_0_0_0_Win Program
Added - Comfort Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature Output Variable
Added - Adaptive Heating Setpoint Temperature Output Variable
Added - Adaptive Cooling Setpoint Temperature_No Tolerance Output Variable
Added - Adaptive Heating Setpoint Temperature_No Tolerance Output Variable
[... 354 lines not shown in the documentation ...]
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
And the total number of output IDFs is going to be 36
Generating the following output IDF files:

TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_1[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_2[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_INT EN16798[CA_3[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_80[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_0.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.1[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.4[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_1.5[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_2[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf
TestModel[CS_AUS DeDear[CA_90[CM_3[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf

=======================END OF OUTPUT IDF FILES GENERATION PROCESS=======================

Now, let's inspect the Output:Variable objects in both the input idf and any of the output idfs, for instance, the first one.

In [36]:
input_testmodel = add_accis_instance.input_idfs['TestModel']
input_testmodel.idfobjects['Output:Variable']

[]

We can see there is no Output:Variable object in the input idf. Now let's see some output idf.

In [37]:
output_testmodel = add_accis_instance.output_idfs[
    'TestModel[CS_INT EN16798[CA_1[CM_0[HM_2[VC_2[VO_0.0[MT_50.0[MW_50.0[AT_0.1[NS_X.idf'
]
output_testmodel.idfobjects['Output:Variable']

[
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Adaptive Cooling Setpoint Temperature_No Tolerance,    !- Variable Name
    Hourly,                   !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Adaptive Heating Setpoint Temperature_No Tolerance,    !- Variable Name
    Hourly,                   !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Zone Operative Temperature,    !- Variable Name
    Hourly,                   !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Adaptive Cooling Setpoint Temperature_No Tolerance,    !- Variable Name
    Runperiod,                !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Adaptive Heating Setpoint Temperature_No Tolerance,    !- Variable Name
    Runperiod,                !- Reporting Frequency
    ;                         !- Schedule Name
,
OUTPUT:VARIABLE,
    *,                        !- Key Value
    Zone Operative Temperature,    !- Variable Name
    Runperiod,                !- Reporting Frequency
    ;                         !- Schedule Name
]

We can see in this case 6 Output:Variable objects, which are the ones we previously requested:
- Zone Operative Temperature
- Adaptive Cooling Setpoint Temperature_No Tolerance
- Adaptive Heating Setpoint Temperature_No Tolerance

in both Hourly and Runperiod Reporting Frequencies.

As usual, let's remove all the output idfs, so that we can re-run the notebook.

In [38]:
for i in os.listdir():
    if i.endswith('.idf') and input_idf[0] not in i:
        os.remove(i)